import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/theme';
import './style.scss';

export const metadata: Metadata = {
  title: "ByteMeuh",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return <html lang="fr">
  <body>
  <AppRouterCacheProvider options={{ enableCssLayer: false }}>
    <ThemeProvider theme={theme}>
      <CssBaseline />
      {props.children}
    </ThemeProvider>
  </AppRouterCacheProvider>
  </body>
  </html>;
}